### ISSUE TITLE
How customisable is this action?

### ISSUE THREAD

**Issue by flamedfury** [katydecorah/seasonal-post-action#95]
Hello @katydecorah :wave: 

I've been looking at this action, as this is the next one to implement. (I love your work :heart: )

If I understand correctly, like the Spotify action, this will create a post at the end of each season. Is there a race condition with the Spotify action? 

I use 11ty rather than Jekyll, but this shouldn't be an issue as the action creates a markdown file with front matter. 

How customisable could this be? Rather than a recipes YAML, I'm saving links to articles to a YAML file called bookmarks.

Does the seasonal post action require each entry in any YAML file to have an image file? I disabled grabbing an image for the bookmarks action as a number of the articles that I saved with the action doesn't have an accompanying image file. A placeholder image could be useful.

In the action, we set `GitHubUsername:` and `GitHubRepository:` to point to where the YAML files are saved. I have this in their own repository, separate from my website repository. Where does the seasonal post markdown file get saved to? Can we have this saved to a different repo? e.g. my website project, and commit to my `src/posts/` directory so that the build process will kick off after the new file has been committed? 

My last question was about your [archive site](https://katydecorah.com/archive/). You mentioned that this is built from a private repo, and you're not ready to share some things. Can you share details about the workflow to create this? 

I thought that if I ran the actions in my website's project repository, I could have a page set up to build out these collection pages based on the YAML files in 11ty's global data directory `src/_data/` to achieve the same result. This could also solve how the seasonal post is built... I'm not sure yet.

Hope this makes sense :blush: ~fLaMEd.

**Comment by katydecorah** [comment]
>  Is there a race condition with the Spotify action?

Yes! I schedule the spotify action to run an hour before this action.

> How customisable could this be? Rather than a recipes YAML, I'm saving links to articles to a YAML file called bookmarks.

Gotcha! I think I could make this customizable.

- [ ] Make "Recipe" specific language customizable for all types of bookmarker

> Does the seasonal post action require each entry in any YAML file to have an image file? I disabled grabbing an image for the bookmarks action as a number of the articles that I saved with the action doesn't have an accompanying image file. A placeholder image could be useful.

Let me double check this!

- [ ] Since bookmark-action can disable images, make sure this action respects that.

> In the action, we set GitHubUsername: and GitHubRepository: to point to where the YAML files are saved. I have this in their own repository, separate from my website repository. Where does the seasonal post markdown file get saved to? Can we have this saved to a different repo? e.g. my website project, and commit to my src/posts/ directory so that the build process will kick off after the new file has been committed?

It sounds like we have the same workflow (correct me if I'm wrong).

1. My read, spotify, and bookmark actions all live in a private repository (archive). The data files are committed to that private repository.
2. This action runs in my public repository: https://github.com/katydecorah/katydecorah.github.io/blob/gh-pages/.github/workflows/season.yml and commits to that public repository.

I'm seeing the the directory path that this action writes to should be an action input so that you could customize where it commits to: https://github.com/katydecorah/seasonal-post-action/blob/5def213f9ea70132928e5b2f049c6113303168ca/src/action.ts#L56-L59 

- [ ] Create an input for the path to write the blog post to


> My last question was about your [archive site](https://katydecorah.com/archive/). You mentioned that this is built from a private repo, and you're not ready to share some things. Can you share details about the workflow to create this?

Of course! Are you looking for templates for how I build out: https://katydecorah.com/archive/books/ using the data files?

**Comment by flamedfury** [comment]
Thank you so much for the detailed reply. I appreciate the help.

> It sounds like we have the same workflow (correct me if I'm wrong).

Yes! Thank you for explaining yours for me. The piece I was missing was running the seasonal action in my website repository. I will get this set up asap.

> I'm seeing the the directory path that this action writes to should be an action input so that you could customize where it commits to:

This would be great I would want to input/output this: `./src/posts/${end}-${year}-${season.toLowerCase()}.md`, 

Is it a stretch to customise the metadata?

> Of course! Are you looking for templates for how I build out: https://katydecorah.com/archive/books/ using the data files?

Yes please. Do these pages generate/build with each time the various actions write to the json files? I should be able to figure out based on what you already have set up.

**Comment by katydecorah** [comment]
> This would be great I would want to input/output this: ./src/posts/${end}-${year}-${season.toLowerCase()}.md,

Excellent! I think this now resolved in #97.

---

> Is it a stretch to customise the metadata?

I just did a refactor that will allow you to customize:
- The markdown template #98 
- The data sources #100

There isn't an official release yet, but I have an example of how to use the new options in a pull request on my site: https://github.com/katydecorah/katydecorah.github.io/pull/357/files 

I hope this will give you the flexibility you need! Let me know what you think. I enjoy working through these ideas. 😀

---

> Yes please. Do these pages generate/build with each time the various actions write to the json files? I should be able to figure out based on what you already have set up.

Since I'm still using Jekyll which uses the default GitHub repository publishing settings, anytime there's a commit to my archive repository GitHub pages will trigger a build. I'm not sure how you have your site set up, but if you're using a GitHub action to build your site, I imagine you can set a similar trigger.

Here are a few templates:
- https://katydecorah.com/archive/ -> https://gist.github.com/katydecorah/b4542ce53c5056ae5e2b8abdea1544a4
- https://katydecorah.com/archive/books/ -> https://gist.github.com/katydecorah/a1fdef7546fd7ee454af8844b2dfaa52
- For my actual seasonal blog posts, there's a reason why the action dumps the yaml in the frontmatter and provides markdown lists:
  - For RSS readers, I want there to be simple lists (as generated by the markdown lists) since you have less control over formatting.
  - For website visitors, I switch the view to a customized the layout with images: https://github.com/katydecorah/theme/blob/main/_includes/post/post-season.html

**Comment by flamedfury** [comment]
I'm looking forward to diving into this over the weekend (fingers crossed).

**Comment by flamedfury** [comment]
I'm checking in and updating you on the progress that I have made. 

I use Eleventy to build my site. When I commit & push to Github, Netlify triggers a build.

I have successfully built two collections pages, [books](https://flamedfury.com/collections/books/) and [articles](https://flamedfury.com/collections/articles/).

I've used the 11ty plugin [eleventy-fetch](https://www.11ty.dev/docs/plugins/fetch/) that allows me to use the _data directory in [flamedfury/metadata-library](https://github.com/flamedfury/metadata-library/) as a global data file in my main website repository [flamedfury/flamedfury.com](https://github.com/flamedfury/flamedfury.com/).

In [flamedfury/flamedfury.com](https://github.com/flamedfury/flamedfury.com/)'s `_data` directory, I create two javascript files that create a collection out of the fetched content, [metadataread.js](fhttps://github.com/flamedfury/flamedfury.com/blob/main/src/_data/metadataread.js) and [metadatabookmarks.js](https://github.com/flamedfury/flamedfury.com/blob/main/src/_data/metadatabookmarks.js).

When I build the website, 11ty fetches the latest data from the `metadata-library`, and the collection pages are rebuilt with the newest content. 

So I don't have to manually trigger a build every time I update the `metadata-library` I have used a Netlify Build Hook and a GitHub Action [trigger-ff-build.yml](https://github.com/flamedfury/metadata-library/blob/main/.github/workflows/trigger-ff-build.yml) that calls the build hook whenever an update is made to the metadata-library.

--- 

Now that the tricky part is out of the way, I can spend some time styling the collections pages and integrating them with the rest of the website. 

It was great to get the [books](https://flamedfury.com/collections/books/) on a single page; I'm not happy with the thumbnails that the `isbn-node` providers have provided. Interesting that some have straight-up failed to download. Have you experienced anything similar? 

I'm keen to spend some time and manually update the metadata so it looks nicer :sweat_smile:

The [articles](https://flamedfury.com/collections/articles/) collection highlights the port state of metadata provided in webpages. The various uses of title, description, author and the image provided are wild :joy: 

---

Now I can get the seasonal post going just in time for March!

**Comment by flamedfury** [comment]
The seasonal post worked! [2023 Summer](https://flamedfury.com/posts/2023-summer/)

I had to change
```yaml
env:
          TOKEN: ${{ secrets.TOKEN }}
```
 to
```yaml
env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
To get it to run.

Will have a look at some of the weird meta data formating for the bookmarks...

**Comment by katydecorah** [comment]
Hey! @flamedfury apologies for the delay! I got really into a side project of learning web components 🙈

---

> The seasonal post worked!

I'm so glad it worked! And thanks for the feedback on the token. I'll update the docs.

---

> I have successfully built two collections pages, [books](https://flamedfury.com/collections/books/) and [articles](https://flamedfury.com/collections/articles/).

🥰 LOVE IT! Have you read [The Murderbot Diaries](https://en.wikipedia.org/wiki/The_Murderbot_Diaries) by Martha Wells? As I browsed your book collection, I thought you may like the series. 

---

> It was great to get the [books](https://flamedfury.com/collections/books/) on a single page; I'm not happy with the thumbnails that the isbn-node providers have provided. Interesting that some have straight-up failed to download. Have you experienced anything similar?

I have not had the problem. I do have an iOS shortcut that will search for a book by title in Google Books and return the best match for the ISBN. This is helpful since I typically read audiobooks. While it doesn't return the exact ISBN for the format I read, I still get a decent result. This result may be different depending on how available the title is in Google Books, unfortunately.

**Comment by flamedfury** [comment]
I have added The Murderbot Diaries to my list (I already did that while browsing your read page :)).

While my manual runs of the action generated the seasonal post, it looks like the scheduled run failed:

```
Write seasonal post
TypeError: Cannot read properties of undefined (reading 'date')
```

I was able to manually run the workflow, leaving the date input blank to use the default date.

![image](https://user-images.githubusercontent.com/4757066/226273809-6cca74ce-7320-4144-821b-d650b9aa37a1.png)

That ran fine :shrug:  :D 

---

Also, for generating the post template you've provided the variables `${bookMarkdown}`, `${playlistMarkdown}`, `${bookmarkMarkdown}`.

How are you customising these to pull in the image files etc?

**Comment by flamedfury** [comment]
@katydecorah <3 thank you so much. I'll check out the two links and see how I can replicate them in 11ty :tada: 

As far as this issue is concerned, I'm happy to close.

I've enjoyed working on this metadata library. I appreciate your patience with my questions. I'm not a developer, and this has been an interesting and exciting challenge to get going on my homepage!

**Comment by katydecorah** [comment]
@flamedfury Glad to hear it! You are the first one to adopt this action, so I thank you for your patience as we sort out bugs 😅. Your feedback has been tremendous.

Please continue to open issues as they arise!
